config/routes.rb
Carriermanager::Application.routes.draw do
  resources :carriers
  resources :origins
  resources :destinations
  resources :courses
  resources :rates
  
  get "welcome/index"
  root "welcome#index"
 end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
	validates :name, presence: true
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :origin
  belongs_to :destination
end

app/models/destination.rb
class Destination < ActiveRecord::Base
  has_many :courses
end

app/models/origin.rb
class Origin < ActiveRecord::Base
	validates :name, presence: true
  has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController
	def new
		@carrier = Carrier.new
	end

	def create
		@carrier = Carrier.new(params[:carrier].permit(:name))

		if @carrier.save
			redirect_to carriers_path
		else
			render 'new'
		end
	end

	def index
		@carriers = Carrier.order(:name).all
	end

	def show
		@carrier = Carrier.find(params[:id])
	end

	def edit
		@carrier = Carrier.find(params[:id])
	end

	def update
		@carrier = Carrier.find(params[:id])

		if @carrier.update(params[:carrier].permit(:name))
			redirect_to @carrier
		else
			render 'edit'
		end
	end

	def destroy
		@carrier = Carrier.find(params[:id])
		@carrier.destroy

		redirect_to carriers_path
	end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(params[:course].permit(:miles, :origin_id, :destination_id))

    if @course.save
      redirect_to courses_path
    else
      render 'new'
    end
  end

  def update
    @course = Course.find(params[:id])

    if @course.update(params[:course].permit(:miles, :origin_id, :destination_id))
      redirect_to @course
    else
      render 'edit'
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    redirect_to courses_path
  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
	def new
		@destination = Destination.new
	end

	def create
		@destination = Destination.new(params[:destination].permit(:name))

		if @destination.save
			redirect_to destinations_path
		else
			render 'new'
		end
	end

	def index
		@destinations = Destination.order(:name).all
	end

	def show
		@destination = Destination.find(params[:id])
	end

	def edit
		@destination = Destination.find(params[:id])
	end

	def update
		@destination = Destination.find(params[:id])

		if @destination.update(params[:destination].permit(:name))
			redirect_to @destination
		else
			render 'edit'
		end
	end

	def destroy
		@destination = Destination.find(params[:id])
		@destination.destroy

		redirect_to destinations_path
	end

end

app/controllers/origins_controller.rb
class OriginsController < ApplicationController
	def new
		@origin = Origin.new
	end

	def create
		@origin = Origin.new(params[:origin].permit(:name))

		if @origin.save
			redirect_to origins_path
		else
			render 'new'
		end
	end

	def index
		@origins = Origin.order(:name).all
	end

	def show
		@origin = Origin.find(params[:id])
	end

	def edit
		@origin = Origin.find(params[:id])
	end

	def update
		@origin = Origin.find(params[:id])

		if @origin.update(params[:origin].permit(:name))
			redirect_to @origin
		else
			render 'edit'
		end
	end

	def destroy
		@origin = Origin.find(params[:id])
		@origin.destroy

		redirect_to origins_path
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/origins_helper.rb
module OriginsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carriers/_form.html.erb
<%= form_for @carrier do |f| %>
	<% if @carrier.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@carrier.errors.count, "error") %> prohibited this post from being saved:</h2>
		<ul>
			<% @carrier.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/carriers/edit.html.erb
<h1>Edit Carrier</h1>

<%= render 'form' %>

<%= link_to 'Back', carriers_path %>

app/views/carriers/index.html.erb
<h1>Carriers</h1>
<p><%= link_to 'New carrier', new_carrier_path %></p>
<ul>
	<% @carriers.each do |carrier| %>
		<li><%= link_to carrier.name, carrier %></li>
	<% end %>
</ul>

app/views/carriers/new.html.erb
<h1>New Carrier</h1>

<%= render 'form' %>

<%= link_to 'Back', carriers_path %>

app/views/carriers/show.html.erb
<h1><%= @carrier.name %></h1>

<p><%= link_to 'Edit', edit_carrier_path(@carrier) %> |
<%= link_to 'Destroy', carrier_path(@carrier),
                    method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', carriers_path %></p>

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
  <% if @course.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@course.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
      <% @course.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
    <p>
      <%= f.label :origin_id %>
      <%= collection_select(:course, :origin_id, Origin.all, :id, :name) %>
    </p>

    <p>
      <%= f.label :destination_id %>
      <%= collection_select(:course, :destination_id, Destination.all, :id, :name) %>
    </p>
    <p>
      <%= f.label :miles %>
      <%= f.text_field :miles %>
    </p>

    <p> 
    <%= f.submit %>
    </p>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Route</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Routes</h1>
<p><%= link_to 'New Route', new_course_path %>
</p>
<table>
<tr>
  <th>Origin</th>
  <th>Destination</th>
  <th>Miles</th>
  <th></th>
</tr>

<% @courses.each do |course| %>
<tr>
  
  <td><%= course.origin.name %></td>
  <td><%= course.destination.name %></td>
  <td><%= course.miles %></td>
  <td><%= link_to 'Show', course %> | <%= link_to 'Edit', edit_course_path(course) %> </td>
</tr>
<% end %>
</table>

app/views/courses/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<h1><%= @course.origin.name %> to <%= @course.destination.name %></h1>
<p>Mileage: <%= @course.miles %></p>

<p>
  <%= link_to 'Edit', edit_course_path(@course) %> | 
  <%= link_to 'Back', courses_path %> | 
  <%= link_to 'Destroy', course_path(@course),
                    method: :delete, data: { confirm: 'Are you sure?' } %>

</p>

app/views/destinations/_form.html.erb
<%= form_for @destination do |f| %>
	<% if @destination.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@destination.errors.cout, "error") %> prohibited this post from being saved: </h2>
			<ul>
				<% @destination.errors.full_message.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/destinations/edit.html.erb
<h1>Edit Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<h1>Destinations</h1>
<p><%= link_to 'New destination', new_destination_path %></p>
<ul>
	<% @destinations.each do |destination| %>
		<li><%= link_to destination.name, destination %></li>
	<% end %>
</ul>

app/views/destinations/new.html.erb
<h1>New Destinations</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<h1><%= @destination.name %></h1>

<p><%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Destroy', destination_path(@destination),
                    method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', destinations_path %></p>

app/views/layouts/_header.html.erb
<h1>Carrier Manager</h1>

app/views/layouts/_navigation.html.erb
<ul class="nav">
	<li><%= link_to 'Home', root_path %></li>
	<li><%= link_to 'Carriers', carriers_path %></li>
	<li><%= link_to 'Origins', origins_path %></li>
	<li><%= link_to 'Destinations', destinations_path %></li>
	<li><%= link_to 'Routes', courses_path %></li>
	<li><%= link_to 'Rates', '#' %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carrier Manager</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<%= render 'layouts/header' %>
      	<%= render 'layouts/navigation' %>
    </header>

	<%= yield %>

	<%= render 'layouts/footer' %>
</body>
</html>

app/views/origins/_form.html.erb
<%= form_for @origin do |f| %>
	<% if @origin.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@origin.errors.cout, "error") %> prohibited this post from being saved: </h2>
			<ul>
				<% @origin.errors.full_message.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/origins/edit.html.erb
<h1>Edit Carrier</h1>

<%= render 'form' %>

<%= link_to 'Back', origins_path %>

app/views/origins/index.html.erb
<h1>Origins</h1>
<p><%= link_to 'New origin', new_origin_path %></p>
<ul>
	<% @origins.each do |origin| %>
		<li><%= link_to origin.name, origin %></li>
	<% end %>
</ul>

app/views/origins/new.html.erb
<h1>New Origin</h1>

<%= render 'form' %>

<%= link_to 'Back', origins_path %>

app/views/origins/show.html.erb
<h1><%= @origin.name %></h1>

<p><%= link_to 'Edit', edit_origin_path(@origin) %> |
<%= link_to 'Destroy', origin_path(@origin),
                    method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', origins_path %></p>

app/views/welcome/index.html.erb
<p>This site is under construction</p>